run '~/.tmux/plugins/tpm/tpm'

# Plugins
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g mouse off
set -g mode-keys vi

# Use system clipboard
set -s set-clipboard on

# Vim-style keybindings
set -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

set-option -sg escape-time 10
set-option -g focus-events on
set-option -sa terminal-features ',xterm-256color:RGB'
set-option -g history-limit 10000

# Nicer scrolling
bind-key Right next-window
# Bind left arrow to go to previous window
bind-key Left previous-window

# Allow tmux to set the terminal title
set -g set-titles on
set -g set-titles-string 'tmux: #{session_name} | #{pane_current_command}'
