wallpaper {
    monitor =
    path = ~/.config/hypr/wallpaper/jellyfish.jpg
    fit_mode = cover
}

wallpaper {
    monitor = desc:ASUSTek COMPUTER INC MB16AHV T8LMCD002261
    path = ~/.config/hypr/wallpaper/jellyfish-vertical.jpg
    fit_mode = cover
}
