preload = ~/.config/hypr/wallpaper/jellyfish.jpg
preload = ~/.config/hypr/wallpaper/jellyfish-vertical.jpg

wallpaper = ,~/.config/hypr/wallpaper/jellyfish.jpg
wallpaper = desc:ASUSTek COMPUTER INC MB16AHV T8LMCD002261,~/.config/hypr/wallpaper/jellyfish-vertical.jpg
